# Generated by Django 5.1.4 on 2024-12-06 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('priority', models.CharField(db_index=True, max_length=20)),
                ('severity', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension_key', models.CharField(max_length=100)),
                ('dimension_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='csttapp.analytics')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('metric_value', models.FloatField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='csttapp.analytics')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('preferences', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DefectHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_index=True, max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='csttapp.defect')),
                ('changed_by_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csttapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='assigned_to_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to='csttapp.profile'),
        ),
        migrations.AddField(
            model_name='defect',
            name='reported_by_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to='csttapp.profile'),
        ),
        migrations.AddField(
            model_name='defect',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='csttapp.project'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='csttapp.project'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csttapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='csttapp.team'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(db_index=True, max_length=20)),
                ('type', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_by_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csttapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='analytics',
            name='test_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='csttapp.testcase'),
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('data_template', models.JSONField()),
                ('format_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csttapp.profile')),
                ('test_cases', models.ManyToManyField(related_name='test_data', to='csttapp.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('notes', models.TextField()),
                ('environment_data', models.JSONField(default=dict)),
                ('executed_by_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='csttapp.profile')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='csttapp.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.IntegerField(db_index=True)),
                ('action', models.TextField()),
                ('expected_result', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='csttapp.testcase')),
            ],
            options={
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='StepResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('actual_result', models.TextField()),
                ('notes', models.TextField()),
                ('attachments', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='csttapp.testexecution')),
                ('test_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csttapp.teststep')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='csttapp.project')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='csttapp.testsuite'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='test_suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='csttapp.testsuite'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='csttapp.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='csttapp.team')),
            ],
            options={
                'unique_together': {('team', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='DefectLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_links', to='csttapp.defect')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_links', to='csttapp.testcase')),
            ],
            options={
                'unique_together': {('defect', 'test_case')},
            },
        ),
    ]
