# Generated by Django 5.1.4 on 2024-12-06 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csttapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='analyticsdimension',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='analyticsdimension',
            name='dimension_key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='analyticsdimension',
            name='dimension_value',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='analyticsmetric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='defecthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='defectlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stepresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='format_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='completed_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['project', 'recorded_at'], name='csttapp_ana_project_67be31_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['test_suite', 'recorded_at'], name='csttapp_ana_test_su_50cc48_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['test_case', 'recorded_at'], name='csttapp_ana_test_ca_a38cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdimension',
            index=models.Index(fields=['analytics', 'dimension_key'], name='csttapp_ana_analyti_399742_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdimension',
            index=models.Index(fields=['dimension_key', 'dimension_value'], name='csttapp_ana_dimensi_b55b42_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['analytics', 'metric_name'], name='csttapp_ana_analyti_6a5b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['metric_name', 'created_at'], name='csttapp_ana_metric__2d6b00_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['created_at', 'metric_value'], name='csttapp_ana_created_f7dbc8_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['analytics', 'created_at'], name='csttapp_ana_analyti_52fc68_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsmetric',
            index=models.Index(fields=['metric_name', 'metric_value'], name='csttapp_ana_metric__9b613f_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['status', 'priority', 'severity'], name='csttapp_def_status_4e8017_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['project', 'status'], name='csttapp_def_project_8c2b83_idx'),
        ),
        migrations.AddIndex(
            model_name='defect',
            index=models.Index(fields=['assigned_to_profile', 'status'], name='csttapp_def_assigne_df47ae_idx'),
        ),
        migrations.AddIndex(
            model_name='defecthistory',
            index=models.Index(fields=['defect', 'field_name'], name='csttapp_def_defect__5945af_idx'),
        ),
        migrations.AddIndex(
            model_name='defecthistory',
            index=models.Index(fields=['defect', 'created_at'], name='csttapp_def_defect__3d1f28_idx'),
        ),
        migrations.AddIndex(
            model_name='defectlink',
            index=models.Index(fields=['defect', 'test_case'], name='csttapp_def_defect__f180d6_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role', 'created_at'], name='csttapp_pro_role_c77cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_active'], name='csttapp_pro_status_e29c49_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team', 'status', 'is_active'], name='csttapp_pro_team_id_d9dd62_idx'),
        ),
        migrations.AddIndex(
            model_name='stepresult',
            index=models.Index(fields=['execution', 'status'], name='csttapp_ste_executi_1a3086_idx'),
        ),
        migrations.AddIndex(
            model_name='stepresult',
            index=models.Index(fields=['test_step', 'status'], name='csttapp_ste_test_st_d06d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name', 'is_active'], name='csttapp_tea_name_e4d1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_at', 'is_active'], name='csttapp_tea_created_4fb51d_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'profile', 'is_active'], name='csttapp_tea_team_id_cf95c3_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['role', 'joined_at'], name='csttapp_tea_role_58d842_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['suite', 'status', 'priority'], name='csttapp_tes_suite_i_23a5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['created_at', 'status'], name='csttapp_tes_created_621aa2_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['type', 'status'], name='csttapp_tes_type_b3dafb_idx'),
        ),
        migrations.AddIndex(
            model_name='testdata',
            index=models.Index(fields=['format_type', 'is_active'], name='csttapp_tes_format__db5db0_idx'),
        ),
        migrations.AddIndex(
            model_name='testdata',
            index=models.Index(fields=['name', 'format_type'], name='csttapp_tes_name_3eaf2b_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['test_case', 'status'], name='csttapp_tes_test_ca_f9e890_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['started_at', 'completed_at'], name='csttapp_tes_started_c7368f_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['executed_by_profile', 'status'], name='csttapp_tes_execute_7b5253_idx'),
        ),
        migrations.AddIndex(
            model_name='teststep',
            index=models.Index(fields=['test_case', 'order_number'], name='csttapp_tes_test_ca_f97ded_idx'),
        ),
        migrations.AddIndex(
            model_name='teststep',
            index=models.Index(fields=['test_case', 'is_active'], name='csttapp_tes_test_ca_0facf1_idx'),
        ),
        migrations.AddIndex(
            model_name='testsuite',
            index=models.Index(fields=['project', 'is_active'], name='csttapp_tes_project_7ff5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='testsuite',
            index=models.Index(fields=['name', 'project'], name='csttapp_tes_name_f8ab2e_idx'),
        ),
    ]
