# Generated by Django 5.1.4 on 2024-12-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csttapp', '0003_teaminvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='generation_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_image',
            field=models.ImageField(blank=True, null=True, upload_to='test_cases/images/'),
        ),
    ]
